### ISSUE TITLE
Regression boundingbox calculation error(0.17 work but 0.17.1 failed)

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#596] opened 2021-12-29 04:27 UTC
**Describe the bug**
For a dxf, the boundingbox calculation  works in EZDXF0.17 but failed in EZDXF0.17.1

**To Reproduce**
```
from ezdxf import recover
from ezdxf.addons.drawing import matplotlib
from ezdxf import bbox
cache = bbox.Cache()
# Exception handling left out for compactness:
doc, auditor = recover.readfile('test.dxf')
if not auditor.has_errors:
    matplotlib.qsave(doc.modelspace(), 'test.png')

boundingbox = bbox.extents(doc.modelspace(), cache=cache)
print(boundingbox)
```

**Confidential Data**
[test.zip](https://github.com/mozman/ezdxf/files/7787069/test.zip)

**Expected behavior**
In ezdxf 0.17
```
findfont: Font family [''] not found. Falling back to DejaVu Sans.
[(17081.04905040303, 5185.584277215872, -2500.0), (48306.94234426553, 29445.58427721587, 1250.0)]
```
In ezdxf0.17.1
```
Traceback (most recent call last):
  File "E:\test\test.py", line 10, in <module>
    boundingbox = bbox.extents(doc.modelspace(), cache=cache)
  File "E:\Python\Python39\lib\site-packages\ezdxf\bbox.py", line 141, in extents
    for box in multi_flat(entities, flatten=flatten, cache=cache):
  File "E:\Python\Python39\lib\site-packages\ezdxf\bbox.py", line 171, in multi_flat
    box = extends_([entity])
  File "E:\Python\Python39\lib\site-packages\ezdxf\bbox.py", line 161, in extends_
    for _box in multi_recursive(entities_, flatten=flatten, cache=cache):
  File "E:\Python\Python39\lib\site-packages\ezdxf\bbox.py", line 118, in multi_recursive
    box = BoundingBox(vertices(primitive))
  File "E:\Python\Python39\lib\site-packages\ezdxf\math\bbox.py", line 22, in __init__
    self.extmin, self.extmax = self.extends_detector(vertices)
  File "E:\Python\Python39\lib\site-packages\ezdxf\math\bbox.py", line 148, in extends_detector
    return extends3d(vertices)
  File "E:\Python\Python39\lib\site-packages\ezdxf\math\bbox.py", line 268, in extends3d
    for v in vertices:
  File "E:\Python\Python39\lib\site-packages\ezdxf\disassemble.py", line 154, in vertices
    yield from self.entity.flattening(self.max_flattening_distance)  # type: ignore
  File "E:\Python\Python39\lib\site-packages\ezdxf\math\ellipse.py", line 404, in flattening
    yield from subdiv(start_point, end_point, param, next_end_param)
  File "E:\Python\Python39\lib\site-packages\ezdxf\math\ellipse.py", line 374, in subdiv
    if distance_point_line_3d(m, s, e) < distance:
  File "E:\Python\Python39\lib\site-packages\ezdxf\math\construct3d.py", line 146, in distance_point_line_3d
    raise ZeroDivisionError("Not a line.")
ZeroDivisionError: Not a line.
```

**Screenshots**

**Comment by mozman** [comment] 2021-12-29 08:16
This seems to be fixed in the current development version and also in the latest beta version on PyPI:

checkout `v0.17.b4` for testing:
    
    pip install ezdxf==0.17.2b4

Please close this issue, if can confirm that the issue is fixed in `v0.17.2b4`

This code runs without any exception with `v0.17.2b4`:

```Python
import ezdxf
from ezdxf import bbox

FILE = "596.dxf"

doc = ezdxf.readfile(FILE)
msp = doc.modelspace()
bounding_box = bbox.extents(msp)
msp.add_lwpolyline(
    bounding_box.rect_vertices(), close=True, dxfattribs={"color": 6}
)
doc.saveas(FILE.replace(".dxf", ".1.dxf"))

```
The file `596.1.dxf`:

![image](https://user-images.githubusercontent.com/4230966/147640665-5c671836-c622-451b-876c-c25a846a7b82.png)

**Closed** 2021-12-30 01:57 UTC
