### ISSUE TITLE
HATCH rendering bug in the drawing add-on

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#454] opened 2021-06-03 09:39 UTC
[test.zip](https://github.com/mozman/ezdxf/files/6590604/test.zip)
```python
import matplotlib.pyplot as plt
from ezdxf import recover
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
dxf_doc, dxf_auditor= recover.readfile('test.dxf')
fig = plt.figure(dpi=200)
ax = fig.add_axes([0, 0, 1, 1])
ax.margins(0)
ctx = RenderContext(dxf_doc)
ctx.current_layout.set_colors(bg='#FFFFFF')
out = MatplotlibBackend(ax)
Frontend(ctx, out).draw_layout(dxf_doc.modelspace(), finalize=True)
fig.savefig('test.png')
```

This is the code result:
![test](https://user-images.githubusercontent.com/5702248/120623693-87f23980-c492-11eb-904f-e37f530ffbcf.png)

This is the AutoCad result:
![1622713172(1)](https://user-images.githubusercontent.com/5702248/120623853-b07a3380-c492-11eb-9378-66631a0ec8b3.png)

**Comment by chibai** [comment] 2021-06-03 09:42
I'm Mr Bug-Producer

**Comment by mozman** [comment] 2021-06-04 03:23
What is your workflow to create your CAD drawings?

**Comment by chibai** [comment] 2021-06-04 03:36
> What is your workflow to create your CAD drawings?
[test_simplified.zip](https://github.com/mozman/ezdxf/files/6595595/test_simplified.zip)

I'm sorry. I'm not the auther of dxf file and the workflow is not recordable.
I smiplified the dxf to the bug HATCH entity, hope it can be helpful.

**Comment by mozman** [comment] 2021-06-04 03:57
I just wanted to know how this HATCH was created because this is not a result that a human would create on purpose.

**Comment by chibai** [comment] 2021-06-04 04:12
> I just wanted to know how this HATCH was created because this is not a result that a human would create on purpose.

Well, I guess it's a work of my unskilled colleague. 
But I really don't know how the HATCH is created......

**Comment by mozman** [comment] 2021-06-04 04:38
This is the degenerated path boundary paths which causes the problem. I have no idea how to filter out such (erroneous) boundary paths like AutoCAD and BricsCAD do.

![image](https://user-images.githubusercontent.com/4230966/120744981-7ba2c680-c4fc-11eb-93c3-17370980191d.png)

This is the edge path (path of single lines) without connection lines added by ezdxf:

![image](https://user-images.githubusercontent.com/4230966/120745859-4a2afa80-c4fe-11eb-89c5-7de0f9ded4e2.png)

Ezdxf is designed to create always connected paths, if the following line element has no common point with the previous line element, ezdxf adds automatically a line segment from the previous end to the following start.

I don't think I will add a logic to detect these degenerated paths, there are infinite possibilities for such paths and frankly I also have no idea how to do that.

**Comment by chibai** [comment] 2021-06-04 04:41
Got it, thank your for telling me this!

**Comment by mozman** [comment] 2021-06-04 04:46
Not so fast young padawan - maybe I have an idea later.

**Comment by chibai** [comment] 2021-06-04 04:48
> Not so fast young padawan - maybe I have an idea later.

I think you could foucus more on some general problems.
And I don't want this specific rare bug to waste your time.

**Comment by mozman** [comment] 2021-06-04 05:27
But this is **real** programming task, most of the other problems are: how to write the damn DXF tags to make AutoCAD happy, or how to interpret or render a special DXF tag.

**Comment by mozman** [comment] 2021-06-04 09:03
Some new insights:

```Python
from pathlib import Path
import ezdxf

DIR = Path("~/Desktop/Outbox").expanduser()

doc = ezdxf.new()
msp = doc.modelspace()
msp.add_lwpolyline([(0, 0), (1, 0), (1, 1), (0, 1)], close = True)
hatch = msp.add_hatch(1)
p = hatch.paths.add_edge_path()
# 2 open segments
p.add_line((0, 1), (1, 1))
p.add_line((1, 1), (0, 1))
p.add_line((0, 1), (0, 0))
p.add_line((0, 0), (0, 1))
doc.set_modelspace_vport(2, center=(0.5, 0.5))
doc.saveas(DIR / "hatch_edge_with_open_segments.dxf")

hatch = msp.add_hatch(1)
p = hatch.paths.add_edge_path()
# 1st loop: closed segments
p.add_line((0, 0), (0, 1))
p.add_line((0, 1), (1, 1))
p.add_line((1, 1), (0, 1))
p.add_line((1, 0), (0, 0))
doc.saveas(DIR / "hatch_edge_with_one_closed_loop.dxf")

# 2nd loop: closed segments
p.add_line((2, 0), (3, 0))
p.add_line((3, 0), (3, 1))
p.add_line((3, 1), (2, 1))
p.add_line((2, 1), (2, 0))
doc.saveas(DIR / "hatch_edge_with_two_closed_loops.dxf")
```
`hatch_with_open_segments.dxf` does not render a `HATCH`:
![image](https://user-images.githubusercontent.com/4230966/120774656-c6373980-c522-11eb-9dbd-d68279bb12d8.png)

`hatch_edge_with_one_closed_loop.dxf` renders the expected `HATCH`:
![image](https://user-images.githubusercontent.com/4230966/120774836-f383e780-c522-11eb-81c6-399a75ef1a73.png)

`hatch_edge_with_two_closed_loops.dxf` renders the weird and unexpected `HATCH`, same result in AutoCAD and BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/120775245-507f9d80-c523-11eb-952d-7796c5af1612.png)

I can can easily remove open segments from the edge path, and render only closed loops, but I think I can not reproduce the result for the two closed loops at the same edge path. My solution will render two separated squares/loops.

**Comment by mozman** [comment] 2021-06-04 11:00
The current solution renders this for the two loops:
![image](https://user-images.githubusercontent.com/4230966/120791070-03f08e00-c534-11eb-923e-2ade64d0825b.png)

and this for the example DXF:
![image](https://user-images.githubusercontent.com/4230966/120791177-27b3d400-c534-11eb-9393-4624918e2c20.png)

**Comment by chibai** [comment] 2021-06-04 11:01
Thanks very much！！

**Comment by mozman** [comment] 2021-06-04 11:09
I leave this issue open for a while. I am afraid this is not the end of the road!

Where do you live/work?

**Comment by chibai** [comment] 2021-06-07 01:32
> I leave this issue open for a while. I am afraid this is not the end of the road!
> 
> Where do you live/work?

I was born and grew up in small citi of Dongyang, Zhejiang province of China 
And now I'm living and working in Shanghai, China
How about U?

**Comment by mozman** [comment] 2021-06-07 02:34
I am from Austria, Graz.

I only asked because I was surprised by your quick answers during my work day that didn't quite match my assumption that you were from China.

**Comment by chibai** [comment] 2021-06-07 03:04
[test_hatch.zip](https://github.com/mozman/ezdxf/files/6605558/test_hatch.zip)
I think I found another hatch bug?
ezdxf drawing
![test](https://user-images.githubusercontent.com/5702248/120953430-81f4a500-c77f-11eb-8e7f-2d63a4e387e5.png)
AutoCad showing
![1623034668(1)](https://user-images.githubusercontent.com/5702248/120953462-93d64800-c77f-11eb-94e8-0f86b4e4f11c.png)


I only answer in my work time, which is 10:am to 7:pm(GMT+8).
I hope one day I can have time to dig into this code and make contribution on this dxf community!

**Comment by mozman** [comment] 2021-06-07 05:34
BricsCAD shows also another result:
![image](https://user-images.githubusercontent.com/4230966/120963848-9d04ec00-c762-11eb-9d9d-214a5551f5e6.png)

I'll look at the DXF file later.

**Comment by mozman** [comment] 2021-06-07 13:47
1. AutoCAD renders a line where no line should be. BricsCAD perfectly subtracts the inner rectangle from the outer shape, as I would expect. Maybe that is a battleground for a war about "boundary" conditions :)
![image](https://user-images.githubusercontent.com/4230966/121025313-508ed000-c7a5-11eb-86ef-f1cdbd1588a2.png)

2. Matplotlib and PyQt handle overlapping paths differently than CAD applications. This are the same boundary paths and even the simple island detection of *ezdxf*  works as expected for this example, but the rendering of the Qt-backend is different to BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/121025461-7b792400-c7a5-11eb-9f3e-ecc1e9aead92.png)

I'm afraid there is nothing I can do about it.

**Comment by mozman** [comment] 2021-06-07 14:09
This code snippet shows how I isolated such entities form the source document:

```Python
from pathlib import Path
import ezdxf

DIR = Path("~/Desktop/Now/ezdxf").expanduser()

doc = ezdxf.readfile(DIR / "chibai04.dxf")
hatch = doc.entitydb.get("1D19")  # get entity by handle

doc2 = ezdxf.new()
msp2 = doc2.modelspace()
msp2.add_foreign_entity(hatch)  # unlinks and unbinds hatch from the source doc!
doc2.saveas(DIR / "isolated_hatch.dxf")
```

This is not a general recommendation to do this, because this is only **sometimes**  useful if the context is not important for the issue like for the last example and zipped DXF files are really small. And it only works if the CAD application shows the entity handle like BricsCAD:

![image](https://user-images.githubusercontent.com/4230966/121030731-09efa480-c7aa-11eb-9c47-4bf04c360b6d.png)

**Comment by chibai** [comment] 2021-06-08 01:51
got it!

**Comment by chibai** [comment] 2021-06-09 03:05
[test_missing_hatch.zip](https://github.com/mozman/ezdxf/files/6620825/test_missing_hatch.zip)
Dear mozman @mozman 
found another one
Missing Circle Hatch
EZDXF drawing result
![test](https://user-images.githubusercontent.com/5702248/121286482-7be2fd80-c912-11eb-938d-36d8cce65bb6.png)
autocad showing
![1623207912(1)](https://user-images.githubusercontent.com/5702248/121286588-9cab5300-c912-11eb-8d58-005dc1d6efdc.png)

**Comment by mozman** [comment] 2021-06-09 06:02
This should be fixed.

**Comment by chibai** [comment] 2021-06-09 09:24
> This should be fixed.
@mozman 
``` python
from ezdxf import recover
from ezdxf.entities import Insert, Hatch, EdgePath, LineEdge


def process_hatch(entity: Hatch):
    available_boudPaths = list(entity.paths.rendering_paths(hatch_style=entity.dxf.hatch_style))
    for path in available_boudPaths:
        if isinstance(path, EdgePath):
            for edge in path.edges:
                if isinstance(edge, LineEdge):
                    print(entity.ocs().to_wcs(edge.start))

def process_insert(entity: Insert):
    for e in entity.virtual_entities():
        entity_type = e.dxftype()
        if entity_type == 'INSERT':
            process_insert(e)
        elif entity_type == 'HATCH':
            process_hatch(e)

dxf_doc, dxf_auditor= recover.readfile('test_missing_hatch.dxf')

for e in dxf_doc.modelspace():
    if e.dxf.invisible == 0:
        entity_type = e.dxftype()
        if entity_type == 'HATCH':
            process_hatch(e)
        elif entity_type == 'INSERT':
            process_insert(e)
```

Please try this code , must be something wrong by #454
![1623230617(1)](https://user-images.githubusercontent.com/5702248/121329131-81a70600-c947-11eb-8b2d-cd6dfaf7a0a9.png)

**Comment by mozman** [comment] 2021-06-09 09:57
`ocs.to_wcs()` requires a vector with x-,  y- and and z-axis, wrap it by `ezdxf.matzh.Vec3()`.

**Comment by chibai** [comment] 2021-06-09 09:57
> `ocs.to_wcs()` requires a vector with x-, y- and and z-axis, wrap it by `ezdxf.matzh.Vec3()`.

ok!

**Comment by mozman** [comment] 2021-06-09 10:19
Added safety castings to `Vec3()` to the transformation methods of `Matrix44()` for the pure Python implementation to get the same behavior as for the C-extension.

**Closed** 2021-07-01 04:58 UTC
Labels: bug
