### ISSUE TITLE
Boundingbox calculation error

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#595] opened 2021-12-27 11:15 UTC
**Describe the bug**
EZDXF calculate boundingbox error but draw correctyly by this dxf file.

**To Reproduce**
```
from ezdxf import recover
from ezdxf.addons.drawing import matplotlib
from ezdxf import bbox
cache = bbox.Cache()
# Exception handling left out for compactness:
doc, auditor = recover.readfile('s110.dxf')
if not auditor.has_errors:
    matplotlib.qsave(doc.modelspace(), 'test.png')
boundingbox = bbox.extents(doc.modelspace(), cache=cache)
print(boundingbox)
```

**Confidential Data**
[S110.zip](https://github.com/mozman/ezdxf/files/7779908/S110.zip)

**Expected behavior**
It seems the whole boudingbox offset to left 

**Screenshots**
draw result
![test](https://user-images.githubusercontent.com/5702248/147466444-d65dc06d-cccd-4a54-af6c-2a49ea7fdf2c.png)
CAD show result
![1640603472(1)](https://user-images.githubusercontent.com/5702248/147466468-15865928-f2d3-4103-9d7b-e674f7080aeb.png)
CAD show with boundingbox calculate by ezdxf
![1640603462](https://user-images.githubusercontent.com/5702248/147466548-79699082-406d-46fb-b53f-3cdd25876710.png)
The straight white line represent the boudingbox calculate by ezdxf

**Comment by mozman** [comment] 2021-12-29 08:22
This seems to be fixed in `v0.17.2b4`, same as #596 

Please close this issue, if you can confirm that the issue is fixed in v0.17.2b4

![image](https://user-images.githubusercontent.com/4230966/147641526-b5a1eaef-9d6e-473b-961e-9a9056a2aa22.png)

**Comment by mozman** [comment] 2021-12-29 08:30
HINT to speedup bounding box calculation:

Ignore the HATCH entities if they are just used inside of a bounding geometry like in your sample DXF, this has much more impact than using the cache, which is useless if you process the entities just once.

```Python
import ezdxf
from ezdxf import bbox

FILE = "595.dxf"


doc = ezdxf.readfile(FILE)
msp = doc.modelspace()
bounding_box = bbox.extents(msp.query("* !HATCH"))  # ignore HATCH entities
msp.add_lwpolyline(
    bounding_box.rect_vertices(), close=True, dxfattribs={"color": 6}
)
doc.saveas(FILE.replace(".dxf", ".1.dxf"))
```

**Comment by chibai** [comment] 2022-01-10 07:26
This is a very strange issue.
I tried your code to do so.
```
import ezdxf
from ezdxf import bbox

FILE = "s110.dxf"

doc = ezdxf.readfile(FILE)
msp = doc.modelspace()
bounding_box = bbox.extents(msp)
print(bounding_box)
msp.add_lwpolyline(
    bounding_box.rect_vertices(), close=True, dxfattribs={"color": 6}
)
doc.saveas(FILE.replace(".dxf", ".1.dxf"))
```
output
```
PS E:\test> python test.py
[(2722.777099742291, 941.922114034507, 0.0), (55462.77709974257, 37376.92211403453, 0.0)]
```

It do create the right rectangle.
But it really strange
![1641799509(1)](https://user-images.githubusercontent.com/5702248/148730585-f2efd194-7e80-4e8d-9182-c7f30e88283d.png)
The created pink rectangle's left bottom corner has nothing to do with (2722.777099742291, 941.922114034507）

**Comment by mozman** [comment] 2022-01-10 09:55
I don't under stand the problem, these are the entities without the bounding box:

![image](https://user-images.githubusercontent.com/4230966/148746827-c32d3df7-7c16-4501-9c15-37c66ba93348.png)

... and with the calculated bounding box:

![image](https://user-images.githubusercontent.com/4230966/148746754-fcdc1ef7-044e-4235-8234-4131ad23d409.png)

**Comment by chibai** [comment] 2022-01-10 10:29
can you list the coordinate of your calculated bounding box?
You will see it's different from [(2722.777099742291, 941.922114034507, 0.0), (55462.77709974257, 37376.92211403453, 0.0)]

**Comment by mozman** [comment] 2022-01-10 10:50
![image](https://user-images.githubusercontent.com/4230966/148753907-a8d30c8b-4bc0-4a8a-82e6-f5f421fe3214.png)

Reset your current UCS to WCS, enter on the command line: 
UCS W

**Comment by chibai** [comment] 2022-01-10 10:52
Got it!

**Comment by chibai** [comment] 2022-01-24 06:56
Hi， found antoher one on ezdxf 0.17.2
[test.zip](https://github.com/mozman/ezdxf/files/7923300/test.zip)
```
from re import sub
from ezdxf import recover
from ezdxf.addons.drawing import matplotlib
from ezdxf import bbox
cache = bbox.Cache()
# Exception handling left out for compactness:
doc, auditor = recover.readfile('test.dxf')
for entity in doc.modelspace():
    print(entity.dxf.handle)
    sub_bb = bbox.extents([entity])
```
error is on entity 12F23

**Comment by chibai** [comment] 2022-01-24 07:16
[test1.zip](https://github.com/mozman/ezdxf/files/7923437/test1.zip)
This has the same problem with entity 2404.

Did matplitlib new version make the bug??

**Comment by mozman** [comment] 2022-01-24 16:33
I cannot reproduce the errors, because these errors depends on a certain font. The only thing I can do is to catch all `Exceptions` raised by `Matplotlib`.

**Closed** 2022-01-25 03:27 UTC
